"""Create initial schema

Revision ID: e74866638288
Revises: 
Create Date: 2026-07-15 00:12:57.613343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74866638288'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgcrypto extension for gen_random_uuid()
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("display_name != ''", name='_display_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'email', name='auth_provider_type'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=256), nullable=True),
    sa.Column('provider_email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_email', name='_provider_email_uc'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='_provider_user_id_uc'),
    sa.UniqueConstraint('user_id', 'provider', name='_user_provider_uc')
    )
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('cover_r2_path', sa.String(length=2048), nullable=True),
    sa.Column('original_file_r2_path', sa.String(length=2048), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'epub', name='book_file_type'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'validating', 'extracting_text', 'detecting_chapters', 'generating_audio', 'completed', 'error', 'deleted', name='book_status'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(file_type != 'epub'::book_file_type) OR (file_size_bytes <= 20971520)", name='chk_epub_size'),
    sa.CheckConstraint("(file_type != 'pdf'::book_file_type) OR (file_size_bytes <= 52428800)", name='chk_pdf_size'),
    sa.CheckConstraint('chapter_count >= 0', name='_chapter_count_nonnegative'),
    sa.CheckConstraint('file_size_bytes > 0', name='_file_size_positive'),
    sa.CheckConstraint('page_count IS NULL OR (page_count BETWEEN 1 AND 300)', name='_page_count_range'),
    sa.CheckConstraint('total_duration_seconds IS NULL OR total_duration_seconds > 0', name='_duration_positive'),
    sa.CheckConstraint('word_count IS NULL OR (word_count BETWEEN 1 AND 100000)', name='_word_count_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_monthly_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('conversions_used', sa.SmallInteger(), nullable=False),
    sa.Column('conversions_limit', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('conversions_limit > 0', name='_conversions_limit_positive'),
    sa.CheckConstraint('conversions_used <= conversions_limit', name='chk_conversions_not_exceeded'),
    sa.CheckConstraint('conversions_used >= 0', name='_conversions_used_nonnegative'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='_month_range_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='_user_year_month_uc')
    )
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('chapter_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_status', sa.Enum('pending', 'generating', 'completed', 'error', 'deleted', name='chapter_audio_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chapter_number >= 0', name='_chapter_number_nonnegative'),
    sa.CheckConstraint('estimated_duration_seconds IS NULL OR estimated_duration_seconds > 0', name='_duration_positive'),
    sa.CheckConstraint('order_index >= 1', name='_order_index_positive'),
    sa.CheckConstraint('word_count >= 0', name='_word_count_nonnegative'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'order_index', name='_book_order_uc')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'validating', 'extracting_text', 'detecting_chapters', 'generating_audio', 'completed', 'error', 'deleted', name='book_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('retry_count >= 0', name='_retry_count_nonnegative'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    op.create_table('chapter_audios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('r2_path', sa.String(length=2048), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending_deletion', 'deleted', name='audio_file_status'), nullable=False),
    sa.Column('tts_voice_id', sa.String(length=128), nullable=True),
    sa.Column('tts_model', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds > 0', name='_duration_positive'),
    sa.CheckConstraint('file_size_bytes > 0', name='_file_size_positive'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id')
    )
    op.create_table('listening_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('position_seconds', sa.Integer(), nullable=False),
    sa.Column('total_listened_seconds', sa.Integer(), nullable=False),
    sa.Column('last_listened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position_seconds >= 0', name='_position_nonnegative'),
    sa.CheckConstraint('total_listened_seconds >= 0', name='_total_listened_nonnegative'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='_user_book_uc')
    )

    # Create partial indexes
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.create_index(op.f('idx_auth_providers_user_id'), 'auth_providers', ['user_id'], unique=False)
    op.create_index(op.f('idx_auth_providers_google_sub'), 'auth_providers', ['provider_user_id'], unique=False, postgresql_where=sa.text("provider = 'google' AND provider_user_id IS NOT NULL"))
    op.create_index(op.f('idx_books_user_id_active'), 'books', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_books_cleanup'), 'books', ['last_accessed_at'], unique=False, postgresql_where=sa.text("status = 'completed' AND deleted_at IS NULL"))
    op.create_index(op.f('idx_books_status'), 'books', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status NOT IN ('completed', 'deleted')"))
    op.create_index(op.f('idx_processing_jobs_status'), 'processing_jobs', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status NOT IN ('completed', 'error')"))
    op.create_index(op.f('idx_chapters_book_order'), 'chapters', ['book_id', 'order_index'], unique=False)
    op.create_index(op.f('idx_chapters_audio_status'), 'chapters', ['book_id', 'audio_status'], unique=False, postgresql_where=sa.text("audio_status IN ('pending', 'error')"))
    op.create_index(op.f('idx_chapter_audios_active'), 'chapter_audios', ['status', 'generated_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('idx_listening_progress_user'), 'listening_progress', ['user_id', 'last_listened_at'], unique=False)

    # Create trigger function for updated_at
    op.execute(
        """
        CREATE OR REPLACE FUNCTION trigger_set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # Create triggers for updated_at on each table
    op.execute("CREATE TRIGGER users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()")
    op.execute("CREATE TRIGGER auth_providers_updated_at BEFORE UPDATE ON auth_providers FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()")
    op.execute("CREATE TRIGGER user_monthly_limits_updated_at BEFORE UPDATE ON user_monthly_limits FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()")
    op.execute("CREATE TRIGGER books_updated_at BEFORE UPDATE ON books FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()")
    op.execute("CREATE TRIGGER processing_jobs_updated_at BEFORE UPDATE ON processing_jobs FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()")
    op.execute("CREATE TRIGGER chapters_updated_at BEFORE UPDATE ON chapters FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()")
    op.execute("CREATE TRIGGER listening_progress_updated_at BEFORE UPDATE ON listening_progress FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop triggers first
    op.execute("DROP TRIGGER IF EXISTS listening_progress_updated_at ON listening_progress")
    op.execute("DROP TRIGGER IF EXISTS chapters_updated_at ON chapters")
    op.execute("DROP TRIGGER IF EXISTS processing_jobs_updated_at ON processing_jobs")
    op.execute("DROP TRIGGER IF EXISTS books_updated_at ON books")
    op.execute("DROP TRIGGER IF EXISTS user_monthly_limits_updated_at ON user_monthly_limits")
    op.execute("DROP TRIGGER IF EXISTS auth_providers_updated_at ON auth_providers")
    op.execute("DROP TRIGGER IF EXISTS users_updated_at ON users")
    op.execute("DROP FUNCTION IF EXISTS trigger_set_updated_at()")

    # Drop partial indexes
    op.drop_index(op.f('idx_listening_progress_user'), table_name='listening_progress')
    op.drop_index(op.f('idx_chapter_audios_active'), table_name='chapter_audios')
    op.drop_index(op.f('idx_chapters_audio_status'), table_name='chapters')
    op.drop_index(op.f('idx_chapters_book_order'), table_name='chapters')
    op.drop_index(op.f('idx_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('idx_books_status'), table_name='books')
    op.drop_index(op.f('idx_books_cleanup'), table_name='books')
    op.drop_index(op.f('idx_books_user_id_active'), table_name='books')
    op.drop_index(op.f('idx_auth_providers_google_sub'), table_name='auth_providers')
    op.drop_index(op.f('idx_auth_providers_user_id'), table_name='auth_providers')
    op.drop_index(op.f('idx_users_email'), table_name='users')

    op.drop_table('listening_progress')
    op.drop_table('chapter_audios')
    op.drop_table('processing_jobs')
    op.drop_table('chapters')
    op.drop_table('user_monthly_limits')
    op.drop_table('books')
    op.drop_table('auth_providers')
    op.drop_table('users')

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS audio_file_status")
    op.execute("DROP TYPE IF EXISTS chapter_audio_status")
    op.execute("DROP TYPE IF EXISTS book_status")
    op.execute("DROP TYPE IF EXISTS book_file_type")
    op.execute("DROP TYPE IF EXISTS auth_provider_type")

    # Drop pgcrypto extension
    op.execute('DROP EXTENSION IF EXISTS "pgcrypto"')
    # ### end Alembic commands ###
